{% set name = "binsider" %}
{% set version = "0.2.0" %}

package:
  name: binsider
  version: {{ version }}

source:
  url: https://github.com/orhun/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f6792950c77795485414a4e82fce7898debed271a4d6fc6e509dc9bfe7879e72

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - binsider --help

about:
  home: https://github.com/orhun/binsider
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
  summary: Analyze ELF binaries like a boss 😼🕵️‍♂️

extra:
  recipe-maintainers:
    - pavelzw
